package com.traductor.popoloca.view.ui.fragments.Code

object DescriptionWords {

    fun descriptionW (lexema: String):String{
        var word=lexema.toLowerCase()

        val description=mapOf( "cha" to "adj  duro \n1.Atho cha niothja thixinꞌa neno tonthai nio. \nEl pan está muy duro; los dientes no aguantan para quebrarlo.\n2. robusto, macizo",
            //CH
            "anseen" to "Duro de corazón \nThi xii atho cha anseen ixin jannee joanchiageꞌe jan na nio ko jeꞌe joajonha nio. \nEl hombre es muy duro de corazón porque su mamá le pidió de caridad una tortilla y él no se la dio.",
            "chaa na" to "Estamos alegres",
            "chaa na" to "Estamos felices",
            "cha'a" to "Estas alegre",
            "cha'a" to "Estas feliz",
            "chaan" to "s 1. Rama (del árbol) Ngain naa chaan nthatsja jointhachjian na columpio. En la rama de un mezquite hicimos un columpio.\n2. penca (de maguey o nopal)\n 3. brazo (del cacto)",
            "chalo" to "chicharrón Are doꞌen na kokochi chonda ke nthachjian na chalo.\n Cuando matamos marranos tenemos que hacer hicharrón.",
            "changi" to "s Collar Tsje nchrii nchexroxiꞌin nchra changi konixin nthachia. \n A muchas mujeres les gustan los collares y los aretes.",
            "chao" to "s Telar",
            "cha'o" to "s 1. pedida, petición (para casarse con una señorita) Jai ndoyo joiaꞌo na chaꞌo ndoꞌa xivecinona ixin joanchia na nchricheꞌe xa. \nHoy en la madrugada vinieron a la casa de mi vecino a pedir a su hija.\n" +
                    "2. flores tiradas en el camino (para honrar a un santo) Are dachrje procesión, naa chojni ditaon nthiꞌa ko thingo tsjo para nchechjian chaꞌo thi datho imagen.\n" +
                    "Cuando hay procesión, una persona va enfrente y tira flores en el camino donde pasa la imagen.",
            "cha'o" to "Petición",
            "charpi" to "s Honda",
            "charpi" to "s Resortera",
            "che" to "adj Picante Nchexroxiꞌin xanꞌna jnanchiixin are jeꞌa atho che. \nA mis hijos les gustan los chiles secos cuando no son muy picantes.",
            "che'e" to "Bandido, Ladrón Jai tjie koee xicheꞌe koxintheꞌe xivecinona. \nHoy en la noche los bandidos robaron el toro de mi vecino.",
            "cheꞌe" to "Bandido, Ladrón Jai tjie koee xicheꞌe koxintheꞌe xivecinona. \n Hoy en la noche los bandidos robaron el toro de mi vecino."
            /*"CIEGO" to "chejo" to "",
            "METAL" to "chia" to "",
            "FIERRO"  to "chia" to "",
            "AGUATE" to "chichao" to "",
            "REFLEJO" to "chiixro" to "",
            "RESPLANDOR" to "chiixro" to "",
            "DISCISIÓN" to "chijni" to "",
            "PLEITO" to "chijni" to "",
            "HEMORROIDES" to "chikin" to "",
            "INFLAMACIÓN" to "chikjan" to "",
            "ENFERMEDAD" to "chin" to "",
            "ALFARECIA" to "chinchjeꞌen" to "",
            "VESTIRSE" to "chinga" to "",
            "CHICLE"  to "chingo" to "",
            "FLECHA" to "chino" to "",
            "NIDO" to "chinthiꞌi" to "",
            "ENCÍA" to "chitangeꞌe" to "",
            "COCERSE" to "chjan" to "",
            "HORNEAR" to "chjan" to "",
            "ASAR" to "chjan" to "",
            "FREÍRSE" to "chjantha" to "",
            "MADURARSE" to "chje" to "",
            "FIAR" to "chje jie" to "",
            "DAR" to "chjee" to "",
            "SUEÑO" to "kothachrin" to "",
            "ROMPERSE" to "chjejin" to "",
            "QUEBRARSE" to "chjejin" to "",
            "DISPERSARSE" to "chjekee" to "",
            "ROTO" to "chjentaon" to "",
            "QUEBRADO" to "chjentaon" to "",
            "SARRO" to "chjiin" to "",
            "CELOSO" to "chjio" to "",
            "DISEÑO" to "chjiꞌni" to "",
            "DIBUJO" to "chjiꞌni" to "",
            "ENVIDIOSO" to "chjoeꞌe" to "",
            "LANA" to "chjon" to "",
            "ESCASO" to "chjonga" to "",
            "ESPERAR" to "choꞌen" to "",
            "PERSONA" to "chojni" to "",
            "GENTE" to "chojni" to "",
            "CACAHUATE" to "chonche" to "",
            "TENER" to "chonda" to "",
            "CALABACITA" to "chondachjan" to "",
            "EXACTAMENTE" to "chongee" to "",
            "PERFECTAMENTE" to "chongee" to "",
            "AFORTUNADO" to "chongeo" to "",
            "SUERTE" to "chongeo" to "",
            "MEDIODÍA" to "chongiixin" to "",
            "CONOCER" to "chonxin" to "",
            //CHR
            "LLENO" to "chre" to "",
            "ESPOSA" to "chriꞌi" to "",
            "BROTAR" to "chriꞌin" to "",
            "LLUVIA" to "chrin" to "",
            "BAJO" to "chringi" to "",
            "REVENTAR" to "tonchintaon to """,
            "REVENTARSE" to "chrintaon" to "",
            "HIELO" to "chrintha" to "",
            "GRANIZO" to "chrintha" to "",
            "NIEVE" to "chrintha" to "",
            "VIENTO" to "chrintho" to "",
            "AIRE" to "chrintho" to "",
            "BONITO" to "chrjoin" to "",
            "BONITA"  to "chrjoin" to "",
            "DICE" to "chro" to "",
            "JUSTICIA" to "chro jie" to "",
            "DEMANDA" to "chro jie" to "",
            "ACUSAR" to "chro jie" to "",
            "NO QUERER" to "chroꞌa" to "",
            "DIJO" to "chroache" to "",
            "ALGO" to "chroan" to "",
            "NO PODER" to "chrojaꞌa" to "",
            //D
            "SACERDOTE" to "daana" to "",
            "PEDAZOS" to "daaña" to "",
            "SUSPIRAR" to "daaba" to "",
            "ENFRIARSE" to "dabeꞌe" to "",
            "GANAR" to "dacha" to "",
            "ENCIMA" to "dachjejin" to "",
            "VIEJO" to "dachrii" to "",
            "SALIR" to "dachrje" to "",
            "APRETAR" to "dagenixin" to "",
            "APLASTAR" to "dagenixin" to "",
            "EXPRIMIR" to "dagenixin" to "",
            "NUERA" to "dainda" to "",
            "BARRER" to "dajon" to "",
            "TEMPRANO" to "dakao" to "",
            "ALUMBRADO" to "dakaon" to "",
            "ENCENDERSE" to "dakin" to "",
            "ANDAR" to "dakji" to "",
            "PEDIR" to "danchia" to "",
            "ROGAR" to "danchiaga'a" to "",
            "SUPLICAR" to "danchiagaꞌa" to "",
            "PREGUNTAR" to "danchiangi" to "",
            "CRECER" to "dangi" to "",
            "DESARROLLAR" to "dangi" to "",
            "BAJAR" to "dania" to "",
            "TIRAR" to "danka" to "",
            "SOPLAR" to "danothe" to "",
            "ABRIR" to "danthjee" to "",
            "ESCURRIR" to "dasiin" to "",
            "TORCER" to "dasinga" to "",
            "AMONTONAR" to "dasintja" to "",
            "MOJARSE" to "data" to "",
            "MEDIR" to "dathechoꞌa" to "",
            "PASAR" to "datho" to "",
            "CRUZAR" to "datho" to "",
            "NADAR" to "dathongi" to "",
            "RECOGER" to "datse" to "",
            "ALZAR" to "datsiin" to "",
            "EMPACAR" to "datsingathe" to "",
            "COSECHA" to "datsinxin" to "",
            "SACAR" to "dantsje" to "",
            "ARRANCAR" to "dantsjengi" to "",
            "RECONOCER" to "datsoan" to "",
            "FERMENTAR" to "datsoxiꞌin" to "",
            "RECIBIR" to "dayee" to "",
            "TRANSPORTAR" to "dayaa" to "",
            "CARGAR" to "dayaa" to "",
            "ACLARAR" to "dechangi" to "",
            "COMPADRE" to "dechjan" to "",
            "CALZAR" to "dechjanga" to "",
            "GUARDAR" to "dechjian" to "",
            "AMARRAR" to "dechria" to "",
            "FAJARSE" to "dechria" to "",
            "MORIR" to "deꞌen" to "",
            "MENSTRUACIÓN" to "egengi" to "",
            "DORMIRSE" to "dejoa" to "",
            "MANEJAR" to "deka" to "",
            "ALCANZAR" to "dekaxin" to "",
            "MERECER" to "dekininxin" to "",
            "CUIDAR" to "denda" to "",
            "PROTEGER" to "denda" to "",
            "EXPULSAR" to "dengi" to "",
            "MATAR" to "denxon" to "",
            "COLGAR" to "deriaꞌnda" to "",
            "ENCONTRARSE"  to "detan" to "",
            "PONER" to "dethea" to "",
            "ARRODILLARSE" to "dethoxin" to "",
            "ENVOLVER" to "detsaa" to "",
            "PONERSE" to "dexrangi" to "",
            "LLEVAR" to "deyaa" to "",
            "CAERSE" to "detsinga" to "",
            "EMBARAZADA" to "deyaa chjan" to "",
            "QUEMADO" to "diche" to "",
            "BEBER" to "di'i" to "",
            "TOMAR" to "diꞌi" to "",
            "BUSCAR" to "dikjee" to "",
            "LLEGAR" to "diji" to "",
            "TRAER" to "dika" to "",
            "VOLVER" to "dikaan" to "",
            "GOLPEADO" to "dikaon" to "",
            "ROBADO" to "dikee" to "",
            "VER" to "dinkon" to "",
            "COMPRAR" to "dina" to "",
            "HACER" to "dinchian" to "",
            "ESCOGER" to "dinchieꞌe" to "",
            "ENCONTRARSE" to "dinchoe" to "",
            "ENCONTRAR" to "dithja" to "",
            "GUSTAR" to "dindatheꞌe" to "",
            "TOCAR" to "dinga" to "",
            "AMANECER" to "dingasaan" to "",
            "TRAGAR" to "dinnga" to "",
            "LABRAR" to "dinthja" to "",
            "ESPARCIR" to "dinthji" to "",
            "JALAR" to "dinthjian" to "",
            "DISOLVER" to "dinthjingi" to "",
            "SALUDO" to "dio" to "",
            "ENVOLVERSE" to "disia" to "",
            "ESTRANGULAR" to "disingeꞌe" to "",
            "ADELANTE"  to "ditaon" to "",
            "PERDIDO" to "ditjaan" to "",
            "OLVIDADO" to "ditjañeꞌe" to "",
            "COCER" to "ditjoa" to "",
            "CAMBIAR" to "ditoxiꞌin" to "",
            "MEZCLAR" to "dithekjan" to "",
            "OBEDECER" to "dithikaon" to "",
            "CUMPLIR" to "dithja" to "",
            "IGUAL" to "dithja" to "",
            "CORROMPER" to "dithje" to "",
            "ENTRAR" to "dixiꞌin" to "",
            "METERSE" to "dixinthe" to "",
            "ABANDONAR" to "dixintonxin" to "",
            "AMONTINARSE" to "dixroinga" to "",
            "PEGAR" to "doen" to "",
            "UTIL" to "donda" to "",
            "SERVIR" to "donda" to "",
            "LIMPIAR" to "doni" to "",
            "ENOJADO" to "doñao" to "",
            "DETERGENTE" to "faa" to "",
            //F
            "AUTOBUS" to "fleecha" to "",
            //G
            "VIUDO" to "ga'an" to "",
            "VIUDA" to "gaꞌan" to "",
            "GARRAFÓN" to "galoon" to "",
            "FOGÓN" to "giꞌi" to "",
            "COSTAL" to "gosta" to "",
            //I
            "MÁS" to "icha" to "",
            "OTRO" to "ijngo" to "",
            "INYECCIÓN" to "inthisioon" to "",
            "PARA" to "ixin" to "",
            //J
            "DESPUÉS" to "ja" to "",
            "SI" to "jaan" to "",
            "HOY" to "jai" to "",
            "RÁPIDAMENTE" to "jaikoa" to "",
            "CUANTO" to "2jaꞌin" to "",
            "PRONTO" to "jaka" to "",
            "MIRA" to "jalajen" to "",
            "ESCONDIDO" to "jima" to "",
            "BUENO" to "janchee" to "",
            "MADRE" to "janna'a" to "",
            "MAMÁ" to "jannaꞌa" to "",
            "ABUELA" to "jannachriꞌi" to "",
            "SUEGRA" to "jannchee" to "",
            "AMANTE" to "janñaokoa" to "",
            "GUAPO" to "jaro" to "",
            "ATRACTIVO" to "jaro" to "",
            "ROJO" to "jatse" to "",
            "AHORITA" to "jaxon" to "",
            "DIFERENTE" to "jee" to "",
            "SOLAMENTE" to "jeꞌo" to "",
            "MALO" to "jianꞌa" to "",
            "DESPACIO" to "jiao" to "",
            "LLENO" to "jichre" to "",
            "GRANDE" to "jie" to "",
            "ES" to "jii" to "",
            "CERRADO" to "jijee" to "",
            "PEINAR" to "jijin" to "",
            "TIERRA" to "jinche" to "",
            "HUMO" to "jiꞌnchin" to "",
            "COMER" to "jine" to "",
            "DESAYUNAR" to "jine" to "",
            "ALMORZAR" to "jine" to "",
            "CENAR" to "jine" to "",
            "MAR" to "jindanchaon" to "",
            "OCÉANO"  to "jindanchaon" to "",
            "MASCAR" to "jinechje" to "",
            "MASTICAR"  to "jinechje" to "",
            "APROVECHARSE" to "jinekoa" to "",
            "ABUSAR" to "jinekoa" to "",
            "ALTO" to "jini" to "",
            "AGUA" to "jinda" to "",
            "ALTURA" to "jinixin" to "",
            "GRUESOS" to "jinjieto" to "",
            "HAMBRE" to "jintha" to "",
            "SUAVEMENTE" to "jion" to "",
            "CUIDADOSAMENTE" to "jion" to "",
            "CONTENER" to "jiria" to "",
            "CONSEGUIR" to "jirika" to "",
            "INCLINANDO" to "jisee" to "",
            "RELAMPAGUEAR" to "jithongixin" to "",
            "FRIJOL" to "jma" to "",
            "HABA" to "jmaaba" to "",
            "CHICHARO" to "jmatholontsin" to "",
            "CERRO" to "jna" to "",
            "AYER" to "jna" to "",
            "MONTAÑA" to "jnanchaꞌan" to "",
            "CHILE" to "jnayoa" to "",
            "SALSA" to "ndajna" to "",
            "CAMPO" to "jngi" to "",
            "TERRENO" to "jngi" to "",
            "SABROSO" to "jni" to "",
            "SANGRE" to "jni" to "",
            "DELGADO" to "jno" to "",
            "TÍA" to "joaꞌa" to "",
            "PERMISO"  to "joachaxin" to "",
            "PREOCUPACIÓN" to "joachjaon" to "",
            "CANCIÓN" to "joadithjaaña" to "",
            "SALUDO" to "joajna" to "",
            "FAVOR" to "joatotseꞌen ñao" to "",
            "MENTE" to "joarrixaon" to "",
            "FLOJERA" to "joaseꞌe" to "",
            "VERGÜENZA"  to "joasoaxin" to "",
            "BRUJERÍA" to "joathoso" to "",
            "DIVINO" to "joatsoꞌen" to "",
            "CHISTE" to "joaxanda" to "",
            "MIEDO" to "joaxraon" to "",
            "DIVERSIÓN" to "joaxroan" to "",
            "MALACATE" to "jochji" to "",
            "CASCO"  to "jocho" to "",
            "CANSANCIO" to "joachrjen" to "",
            "TERMINÉ" to "joena" to "",
            "GÜERA"  to "joera" to "",
            "TRAJO" to "joiaꞌo" to "",
            "HUEVO" to "joja" to "",
            "ANCIANO" to "jonchjan" to "",
            "CHAROLA" to "jonjni" to "",
            //K
            "HIERBA"  to "ka" to "",
            "CALZÓN" to "kacha" to "",
            "PASTO" to "kachji" to "",
            "GORRA" to "kachocha" to "",
            "MAGUEY" to "kachro" to "",
            "ZÁBILA" to "kachronajni" to "",
            "TAMBIÉN" to "kai" to "",
            "TODO" to "kain" to "",
            "PALMA" to "kajne" to "",
            "EPASOTE" to "kamaxra chjiꞌan" to "",
            "HIERBABUENA" to "kamaxra najni" to "",
            "MIRTO"  to "kamirton" to "",
            "ESPINAS" to "nchaꞌa" to "",
            "ABSOLUTAMENTE" to "kanchesinxon" to "",
            "VERDOLAGA" to "kanchexroa" to "",
            "QUELITE" to "kanchexroakoode" to "",
            "PENCA" to "kanchiixin" to "",
            "PAXTLE" to "kanchrjen" to "",
            "PETATE" to "kania" to "",
            "NOPAL" to "kantha" to "",
            "CHICALOTE" to "kanthachikalo" to "",
            "VARIOS" to "kanxin" to "",
            "CANAL"  to "kaño" to "",
            "RUDA" to "karroda" to "",
            "HUARACHE" to "kathe" to "",
            "PEGAJOSA" to "kathinta" to "",
            "MARRUBIO" to "kathochjee konia" to "",
            "BASURA" to "kaxineno" to "",
            "IXTLE" to "kaxra" to "",
            "OBSTRUIR" to "kayakoeꞌen" to "",
            "AMBOS" to "kayoi" to "",
            "FIESTA" to "kiai" to "",
            "FRÍO" to "kin" to "",
            "TRANSFORMAR" to "kjamanga" to "",
            "CAERSE" to "kjamangi" to "",
            "REGRESAR" to "kjan" to "",
            "PAPÁ" to "ndodaa" to "",
            "TÍO" to "chrinina" to "",
            "HIJA" to "Xanꞌna" to "",
            "HIJO" to "Xanꞌna" to "",
            "HERMANA" to "xichian" to "" ,
            "HERMANO" to "ichian" to ""*/


        )
        return if(description[word]!=null){
            description[word].toString()
        }else
            ""
    }
}